---
title: "Problem Section 4"
subtitle:  "Discrete Distributions"
graphics: yes
output: 
      pdf_document:
      highlight: null
      pandoc_args: ["--syntax-highlighting=tango"]
header-includes:
    - \usepackage{amsmath, amssymb}
    - \usepackage{framed}\definecolor{shadecolor}{rgb}{0.949,0.949,0.949}
---

```{r setup, include=FALSE}
#use this code chunk to set global options
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


* * * 
\begin{shaded}

\textbf{Learning Outcomes}

The problems are designed to build conceptual understanding and problem-solving skills. The emphasis is on learning to find, evaluate and build confidence.
The specific tasks include: 

    - Identifying the range of discrete and continuous random variables
   
   - Deriving the PMF and CDF of a discrete random variable
   
   - Recognizing properties of CDFs
   
   - Back up and support work with relevant explanations
   

\end{shaded}

* * *

### Exercises 

1. For each situation, give the range of the random variable $X$. Then state whether the random variable is discrete or continuous.

a. $X$ is the number of employees among 12 recently hired that will still be with the company in another year.
    	
    The range is $\{0,1,2,\dots, 12\}$. $X$ is discrete since it takes finitely many values.
		
b. In a busy 24 hour copy center, minor malfunctions of the copy machine occur randomly. $X$ denotes the time (in hours) until the first minor malfunction occurs.
	 
	 The range is $[0, \infty)$. Here, $X$ can take any value in an interval and can (in theory) be measured with infinite precision. It is a continuous random variable even though it is being rounded to hours.
	 
2. 2. Suppose you toss a fair coin 3 times. The sample space for this experiment is shown below:
$$S = \{ HHH, HHT, HTH, HTT, TTT,TTH, THT, THH \}.$$

a. Let $X$ denote the difference between number of heads and number of tails. Write the PMF of $X$ in a tabular format.   

    \begin{tabular}{|c|c|c|c|c|} \hline
    $x$ & -3 & -1 & 1 & 3 \\ \hline
    $f(x)$ & 1/8 & 3/8 & 3/8 & 1/8 \\ \hline
    \end{tabular}

b. Draw the probability histogram of $X$ in R. Comment on the appearance of the distribution such as shape, modality.

    Students will fill this in during section

3. Which of the following is a valid CDF? (choose one; also point out what's wrong with the ones you didn't choose)

Hint: make a sketch 

a. 
\begin{align*} 
        F(x) &= \left\{ \begin{array}{cc} 
                 0 & x < 0\\ [2pt]
                 \frac{1}{4} & 0 \leq x \leq 3 \\ [2pt]
                 \frac{3}{4} & 3 <  x < 5 \\ [2pt]
                 1 & 5 \leq x \end{array} \right. \end{align*}

    This is not a valid CDF because it is not right continuous at $x=3$. The function should take the value at the top of the jump.
    
b.
\begin{align*} 
        F(x) &= \left\{ \begin{array}{cc} 
                 0 & x < 0\\ [2pt]
                 \frac{1}{4} & 0 \leq x < 3 \\ [2pt]
                 \frac{3}{4} & 3 \leq x < 5 \\ [2pt]
                 1 & 5 \leq x \end{array} \right. \end{align*}

    This is a valid CDF because it is non-decreasing, right continuous, $F(\infty) = 1$ and $F(-\infty) = 0$.

c. 
\begin{align*} 
      F(x) &= \left\{ \begin{array}{cc} 
                 0 & x < 0\\ [2pt]
                 \frac{3}{4} & 0 \leq x < 3 \\ [2pt]
                 \frac{1}{4} & 3 \leq x < 5 \\ [2pt]
                 1 & 5 \leq x \end{array} \right. \end{align*}
   
This is not a valid CDF since it decreases at $x=3$. A CDF is always non-decreasing.


d.
\begin{align*} 
       F(x) &= \left\{ \begin{array}{cc} 
                 0 & x < 0\\ [2pt]
                 \frac{1}{4} & 0 \leq x < 3 \\ [2pt]
                 \frac{3}{4} & 3 \leq x < 5 \\ [2pt]
                 \frac{7}{8} & 5 \leq x \end{array}   
                 \right.                      
\end{align*}              

This is not a valid CDF since it does not converge to 1 as $x \rightarrow \infty$.

4.  Suppose $X$ is a random variable with PMF
$$f(x) = \frac{1}{5} \quad x = 1,2,3,4,5$$

a. Find $F(x)$ the CDF of $X$.

    $$F(x) = \begin{cases}
    0 & x < 1 \\ 
    \frac{1}{5} & 1 \le x < 2 \\ 
    \frac{2}{5} & 2 \le x < 3 \\ 
    \frac{3}{5} & 3 \le x < 4 \\ 
    \frac{4}{5} & 4 \le x < 5 \\ 
       1        & 5 \le x
    \end{cases}$$

b. Use your CDF to find $P(X < 3)$, $P(X = 1)$, $P(X > 2)$ and $P(2 < X \le 4)$. (Note: you can verify your answers by calculating these probabilities using the PMF)

    \begin{align*}
    P(X < 3) &= F(3-) = \lim\limits_{x \uparrow 3} F(x) \\ 
             &= \frac{2}{5} \\
    P(X > 2) &= 1 - P(X \leq 2) = 1 - F(2) \\
             &= 1 - \frac{2}{5} = \frac{3}{5} \\
    P(2 < X \le 4) &= P(X \le 4) - P(X \le 2) = F(4) - F(2)\\
             &= \frac{4}{5} - \frac{2}{5} = \frac{2}{5}.
    \end{align*}  
    


